
###URLs y APIs para el consumo de WS SISTRADOC
#url.ws.authentication=http://localhost:8093/ms-app-ws-authentication/auth/login
url.ws.authentication=http://192.168.18.82/ms-app-ws-authentication/
api.ws.authentication.login=auth/login
api.ws.authentication.health=actuator/health

###URLs y APIs para el consumo de WS SISTRADOC
#url.ws.sistradoc=http://localhost:8090/ms-app-ws-sistradoc/
url.ws.sistradoc=http://192.168.18.82/ms-app-ws-sistradoc/

api.ws.sistradoc.register=api/registerTramite
api.ws.sistradoc.getListTipoTramite=api/getListTipoTramite
api.ws.sistradoc.deriver=api/deriverTramite
api.ws.sistradoc.devolver=api/devolverTramite
api.ws.sistradoc.finished=api/finishedTramite
api.ws.sistradoc.registerTarea=api/registerTareaTramite

api.ws.sistradoc.getListTramiteDeriver=querys/getListTramiteToDeriverByDependency/
api.ws.sistradoc.getListTramiteDevolver=querys/getListTramiteToDevolverByDependency/
api.ws.sistradoc.getListTramiteFinished=querys/getListTramiteToFinishedByDependency/
api.ws.sistradoc.getListTramiteToAttend=querys/getListTramiteToAttendByDependency/
api.ws.sistradoc.getListTramiteByCodigoTramite=querys/getListTramiteFindByCodigoTramite/
api.ws.sistradoc.getListTramiteBySolicitante=querys/getListTramiteFindBySolicitante/
api.ws.sistradoc.getListTramiteByDateRange=querys/getListTramiteFindByDateRange/
api.ws.sistradoc.getListTareasByCodigoTramite=querys/getListTareasByCodigoTramite/
api.ws.sistradoc.getListFlujoTramiteByCodigo=querys/getListFlujoTramiteByCodigo/

api.ws.sistradoc.health=actuator/health
