/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pe.com.softlite.clientsistradoc.view.querys;

import pe.com.softlite.clientsistradoc.dto.LoginResponseDTO;
import pe.com.softlite.clientsistradoc.dto.TramiteQuerysDTO;
import pe.com.softlite.clientsistradoc.process.QuerysTramite;
import pe.com.softlite.clientsistradoc.process.ServicesTramite;
import pe.com.softlite.clientsistradoc.process.imp.QueryTramiteImp;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class DialogBusquedaTramite extends javax.swing.JDialog {

    /**
     * Creates new form DialogConsultTramiteInformation
     */
    public DialogBusquedaTramite(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initProcess();
    }
    
    public DialogBusquedaTramite(java.awt.Frame parent, boolean modal, LoginResponseDTO loginResponseDTO) {
        super(parent, modal);
        this.loginResponseDTO = loginResponseDTO;
        initComponents();
        initProcess();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblArea = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblDependencia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rbCodigoTramite = new javax.swing.JRadioButton();
        rbSolicitante = new javax.swing.JRadioButton();
        rbFechas = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        lblCodigoTramite = new javax.swing.JLabel();
        txtBusquedaCodigoTramite = new javax.swing.JTextField();
        lblTipoDocumento = new javax.swing.JLabel();
        cbBusquedaTipoDocumento = new javax.swing.JComboBox<>();
        lblNroDocumento = new javax.swing.JLabel();
        txtBusquedaNroDocumento = new javax.swing.JTextField();
        lblFechaInicio = new javax.swing.JLabel();
        txtBusquedaFechaInicio = new javax.swing.JTextField();
        lblFechaFin = new javax.swing.JLabel();
        txtBusquedaFechaFin = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListTramites = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jlabelUbicacion = new javax.swing.JLabel();
        txtUbicacionActual = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEstadoTramite = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDiasTranscurridos = new javax.swing.JTextField();
        lblAlerta = new javax.swing.JLabel();
        jlabelFechas = new javax.swing.JLabel();
        txtFechas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblArea.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblArea.setText("Mesa de Partes");

        jLabel1.setText("Area");

        jLabel2.setText("Dependencia");

        jLabel11.setText("Usuario");

        lblNombreUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblNombreUsuario.setText("Luis Noé Lizana Ramírez");

        lblDependencia.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblDependencia.setText("Unidad de trámite documentario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDependencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblNombreUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDependencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblArea))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterios de búsqueda"));

        buttonGroup1.add(rbCodigoTramite);
        rbCodigoTramite.setSelected(true);
        rbCodigoTramite.setText("Por codigo de Tramite");
        rbCodigoTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCodigoTramiteActionPerformed(evt);
            }
        });
        jPanel3.add(rbCodigoTramite);

        buttonGroup1.add(rbSolicitante);
        rbSolicitante.setText("Nro Documento  Solictante");
        rbSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSolicitanteActionPerformed(evt);
            }
        });
        jPanel3.add(rbSolicitante);

        buttonGroup1.add(rbFechas);
        rbFechas.setText("Por Fechas (dd/mm/yyyy)");
        rbFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFechasActionPerformed(evt);
            }
        });
        jPanel3.add(rbFechas);

        lblCodigoTramite.setText("Código de trámite");

        txtBusquedaCodigoTramite.setText("jTextField1");

        lblTipoDocumento.setText("Tipo Documento");

        cbBusquedaTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "CE", "PAS", "RUC" }));

        lblNroDocumento.setText("Nro Documento");

        txtBusquedaNroDocumento.setText("jTextField1");

        lblFechaInicio.setText("Fecha de Inicio");

        txtBusquedaFechaInicio.setText("jTextField1");

        lblFechaFin.setText("Fecha Fin");

        txtBusquedaFechaFin.setText("jTextField2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaInicio)
                    .addComponent(lblTipoDocumento)
                    .addComponent(lblCodigoTramite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbBusquedaTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusquedaFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusquedaCodigoTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNroDocumento)
                    .addComponent(lblFechaFin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBusquedaNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusquedaFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoTramite)
                    .addComponent(txtBusquedaCodigoTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDocumento)
                    .addComponent(cbBusquedaTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNroDocumento)
                    .addComponent(txtBusquedaNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaInicio)
                    .addComponent(txtBusquedaFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaFin)
                    .addComponent(txtBusquedaFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel5.add(btnBuscar);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel5.add(btnNuevo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados de búsqueda"));

        tableListTramites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableListTramites.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListTramitesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableListTramites);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );

        jButton2.setText("Ver tareas realizadas (Pending)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        jlabelUbicacion.setText("Ubicación Actual");

        txtUbicacionActual.setEditable(false);
        txtUbicacionActual.setText("jTextField1");

        jLabel4.setText("Situación de Trámite");

        txtEstadoTramite.setEditable(false);
        txtEstadoTramite.setText("REGISTRADO");

        jLabel9.setText("Duracion de trámite (días)");

        txtDuracion.setEditable(false);
        txtDuracion.setText("999");

        jLabel10.setText("Tiempo transcurrido (días laborales)");

        txtDiasTranscurridos.setEditable(false);
        txtDiasTranscurridos.setText("999");

        lblAlerta.setForeground(new java.awt.Color(0, 0, 204));
        lblAlerta.setText("mensajito mensajito");

        jlabelFechas.setText("Fechas de registro - termino");

        txtFechas.setEditable(false);
        txtFechas.setText("29/09/2024 - 20/10/2024");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jlabelUbicacion)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtDiasTranscurridos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAlerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEstadoTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(81, 81, 81)
                                        .addComponent(jlabelFechas))
                                    .addComponent(txtUbicacionActual, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEstadoTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelFechas)
                    .addComponent(txtFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelUbicacion)
                    .addComponent(txtUbicacionActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtDiasTranscurridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlerta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tableListTramitesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListTramitesMouseClicked
        seleccionar();
    }//GEN-LAST:event_tableListTramitesMouseClicked

    private void rbCodigoTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCodigoTramiteActionPerformed
        opcionCodigoTramite();
    }//GEN-LAST:event_rbCodigoTramiteActionPerformed

    private void rbSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSolicitanteActionPerformed
        opcionNroSolicitante();
    }//GEN-LAST:event_rbSolicitanteActionPerformed

    private void rbFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFechasActionPerformed
        opcionFechas();
    }//GEN-LAST:event_rbFechasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        listarTareas();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogBusquedaTramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogBusquedaTramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogBusquedaTramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogBusquedaTramite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogBusquedaTramite dialog = new DialogBusquedaTramite(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbBusquedaTipoDocumento;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabelFechas;
    private javax.swing.JLabel jlabelUbicacion;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblCodigoTramite;
    private javax.swing.JLabel lblDependencia;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblNroDocumento;
    private javax.swing.JLabel lblTipoDocumento;
    private javax.swing.JRadioButton rbCodigoTramite;
    private javax.swing.JRadioButton rbFechas;
    private javax.swing.JRadioButton rbSolicitante;
    private javax.swing.JTable tableListTramites;
    private javax.swing.JTextField txtBusquedaCodigoTramite;
    private javax.swing.JTextField txtBusquedaFechaFin;
    private javax.swing.JTextField txtBusquedaFechaInicio;
    private javax.swing.JTextField txtBusquedaNroDocumento;
    private javax.swing.JTextField txtDiasTranscurridos;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtEstadoTramite;
    private javax.swing.JTextField txtFechas;
    private javax.swing.JTextField txtUbicacionActual;
    // End of variables declaration//GEN-END:variables

    private LoginResponseDTO loginResponseDTO;
    private ServicesTramite serviceTramite;
    private QuerysTramite queryTramite;
    private List<TramiteQuerysDTO> listTramite;
    private final String cabecera[] = {"COD. TRAMITE", "FECHA REG.", "TIPO TRAMITE", /*"ASUNTO", */"SOLICITANTE"};
    private DefaultTableModel tableModel;
    private int rowNumSelected = -1;
    private DialogListTareasByTramite dialogTareas;
    private String codigoTramite;
    
    private void initProcess() {
        if(queryTramite==null) {
            queryTramite = new QueryTramiteImp();
        }
        if(dialogTareas==null) {
            dialogTareas = new DialogListTareasByTramite(this, true);
        }
        opcionCodigoTramite();
        loadUsuario();
        nuevo();
    }
    
    private void loadUsuario() {
        lblNombreUsuario.setText(loginResponseDTO.getNombreUsuario());
        lblDependencia.setText(loginResponseDTO.getNombreDependencia());
        lblArea.setText(loginResponseDTO.getNombreArea());
    }
    
    private void nuevo() {
        txtBusquedaCodigoTramite.setText("");
        cbBusquedaTipoDocumento.setSelectedIndex(0);
        txtBusquedaNroDocumento.setText("");
        txtBusquedaFechaInicio.setText("");
        txtBusquedaFechaFin.setText("");
        tableModel = new DefaultTableModel(cabecera, 0);
        tableListTramites.setModel(tableModel);
        
        txtEstadoTramite.setText("");
        txtUbicacionActual.setText("");
        txtFechas.setText("");
        txtDuracion.setText("");
        txtDiasTranscurridos.setText("");
        lblAlerta.setText("");
    }
        
    private void buscar() {
        if(rbCodigoTramite.isSelected()) {
            listTramite = queryTramite.listTramitesFindByCodigoTramite(txtBusquedaCodigoTramite.getText());
        }else if(rbSolicitante.isSelected()) {
            listTramite = queryTramite.listTramitesFindBySolicitante(cbBusquedaTipoDocumento.getSelectedItem().toString(), txtBusquedaNroDocumento.getText());
        }else if(rbFechas.isSelected()) {
            String fInic[] = txtBusquedaFechaInicio.getText().split("/");
            String fechaInicio = fInic[2] + "-" + fInic[1] + "-" + fInic[0];
            
            String fFin[] = txtBusquedaFechaFin.getText().split("/");
            String fechaFin = fFin[2] + "-" + fFin[1] + "-" + fFin[0];
            listTramite = queryTramite.listTramitesFindByRangoFechas(fechaInicio, fechaFin);
        }
        
        tableModel = new DefaultTableModel(cabecera, 0);
        
        //String cabecera[] = {"COD. TRAMITE", "FECHA REG.", "TIPO TRAMITE", /*"ASUNTO", */"SOLICITANTE"};
        for(TramiteQuerysDTO t : listTramite) {
            String data[] = {t.getCodigoTramite(), t.getFechaIngreso(), t.getTipoTramite(), /*t.getAsunto(), */t.getSolicitante()};
            tableModel.addRow(data);
        }
        tableListTramites.setModel(tableModel);
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados de búsqueda. (" + listTramite.size() + " trámites)"));
    }
    
    private void seleccionar() {
        rowNumSelected = tableListTramites.getSelectedRow();
        TramiteQuerysDTO tramiteSelected = listTramite.get(rowNumSelected);
//        txtCodigoTramite.setText(tramiteSelected.getCodigoTramite());
//        txtTipoTramite.setText(tramiteSelected.getTipoTramite());
//        txtSolicitante.setText(tramiteSelected.getSolicitante());

        txtEstadoTramite.setText(tramiteSelected.getEstadoTramite());
        txtUbicacionActual.setText(tramiteSelected.getDependenciaActual());
        txtFechas.setText(tramiteSelected.getFechaIngreso() + " - " + (tramiteSelected.getFechaFin()!=null ? tramiteSelected.getFechaFin() : ""));
        txtDuracion.setText(String.valueOf(tramiteSelected.getDuracion()));
        txtDiasTranscurridos.setText(String.valueOf(tramiteSelected.getDiasTranscurridos()));
        codigoTramite = tramiteSelected.getCodigoTramite();
        int diferenciaDias = tramiteSelected.getDuracion() - tramiteSelected.getDiasTranscurridos();
        if(diferenciaDias>0) {
            String mensaje = "Al trámite le quedan " + diferenciaDias + " días";
            lblAlerta.setForeground(new java.awt.Color(0, 0, 204));
            lblAlerta.setText(mensaje);
        }else {
            String mensaje = "Al trámite se ha pasado por  " + diferenciaDias * (-1) + " días";
            lblAlerta.setForeground(new java.awt.Color(255, 0, 0));
            lblAlerta.setText(mensaje);
        }
    }
    
    private void opcionCodigoTramite() {
        lblCodigoTramite.setVisible(true);
        txtBusquedaCodigoTramite.setVisible(true);
        
        lblTipoDocumento.setVisible(false);
        cbBusquedaTipoDocumento.setVisible(false);
        lblNroDocumento.setVisible(false);
        txtBusquedaNroDocumento.setVisible(false);
        lblFechaInicio.setVisible(false);
        txtBusquedaFechaInicio.setVisible(false);
        lblFechaFin.setVisible(false);
        txtBusquedaFechaFin.setVisible(false);
    }
    
    private void opcionNroSolicitante() {
        lblTipoDocumento.setVisible(true);
        cbBusquedaTipoDocumento.setVisible(true);
        lblNroDocumento.setVisible(true);
        txtBusquedaNroDocumento.setVisible(true);
        
        lblCodigoTramite.setVisible(false);
        txtBusquedaCodigoTramite.setVisible(false);
        lblFechaInicio.setVisible(false);
        txtBusquedaFechaInicio.setVisible(false);
        lblFechaFin.setVisible(false);
        txtBusquedaFechaFin.setVisible(false);
    }
    
    private void opcionFechas() {
        lblFechaInicio.setVisible(true);
        txtBusquedaFechaInicio.setVisible(true);
        lblFechaFin.setVisible(true);
        txtBusquedaFechaFin.setVisible(true);
        
        lblCodigoTramite.setVisible(false);
        txtBusquedaCodigoTramite.setVisible(false);
        lblTipoDocumento.setVisible(false);
        cbBusquedaTipoDocumento.setVisible(false);
        lblNroDocumento.setVisible(false);
        txtBusquedaNroDocumento.setVisible(false);
    }
    
    public void listarTareas() {
        dialogTareas.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogTareas.pack();
        dialogTareas.setCodigoTramite(codigoTramite);
        dialogTareas.nuevo();
        dialogTareas.setVisible(true);
        
    }
    
}
