/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pe.com.softlite.clientsistradoc.view.process;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import pe.com.softlite.clientsistradoc.dto.LoginResponseDTO;
import pe.com.softlite.clientsistradoc.dto.TramiteDTO;
import pe.com.softlite.clientsistradoc.dto.TramiteMovimientoDTO;
import pe.com.softlite.clientsistradoc.dto.TramiteQuerysDTO;
import pe.com.softlite.clientsistradoc.process.QuerysTramite;
import pe.com.softlite.clientsistradoc.process.ServicesTramite;
import pe.com.softlite.clientsistradoc.process.imp.QueryTramiteImp;
import pe.com.softlite.clientsistradoc.process.imp.ServicesTramiteImp;
import java.net.http.HttpResponse;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class DialogDerivar extends javax.swing.JDialog {

    /**
     * Creates new form dialogDerivar
     */
    public DialogDerivar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initProcess();
    }
    
    public DialogDerivar(java.awt.Frame parent, boolean modal, LoginResponseDTO loginResponseDTO) {
        super(parent, modal);
        this.loginResponseDTO = loginResponseDTO;
        initComponents();
        initProcess();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblDependencia = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListTramites = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoTramite = new javax.swing.JTextField();
        txtSolicitante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTipoTramite = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMotivoEnvio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDependenciaDestino = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDiasTranscurridos = new javax.swing.JTextField();
        lblAlerta = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Derivar documentos");

        jLabel1.setText("Area");

        jLabel2.setText("Dependencia");

        jLabel11.setText("Usuario");

        lblNombreUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblNombreUsuario.setText("Luis Noé Lizana Ramírez");

        lblDependencia.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblDependencia.setText("Unidad de trámite documentario");

        lblArea.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblArea.setText("Mesa de Partes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDependencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                    .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblNombreUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDependencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblArea))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de trámites a derivar"));

        tableListTramites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableListTramites.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableListTramites.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListTramitesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableListTramites);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tramite a derivar"));

        jLabel4.setText("Código Tramite");

        jLabel5.setText("Solicitante");

        txtCodigoTramite.setEditable(false);

        txtSolicitante.setEditable(false);

        jLabel6.setText("Tipo de trámite");

        txtTipoTramite.setEditable(false);

        jLabel7.setText("Motivo de Envío *");

        txtMotivoEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotivoEnvioActionPerformed(evt);
            }
        });

        jLabel8.setText("Dependencia Destino");

        txtDependenciaDestino.setEditable(false);

        jLabel9.setText("Duracion de trámite (días)");

        txtDuracion.setEditable(false);
        txtDuracion.setText("999");

        jLabel10.setText("Tiempo transcurrido (días laborales)");

        txtDiasTranscurridos.setEditable(false);
        txtDiasTranscurridos.setText("999");

        lblAlerta.setForeground(new java.awt.Color(0, 0, 204));
        lblAlerta.setText("mensajito mensajito");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtCodigoTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSolicitante, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                    .addComponent(txtTipoTramite)
                    .addComponent(txtMotivoEnvio)
                    .addComponent(txtDependenciaDestino)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiasTranscurridos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAlerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtCodigoTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTipoTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMotivoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDependenciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtDiasTranscurridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlerta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegistrar.setText("Derivar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegistrar);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel4.add(btnNuevo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableListTramitesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListTramitesMouseClicked
        seleccionarTramite();
    }//GEN-LAST:event_tableListTramitesMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        procesar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtMotivoEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotivoEnvioActionPerformed
        procesar();
    }//GEN-LAST:event_txtMotivoEnvioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogDerivar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogDerivar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogDerivar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogDerivar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogDerivar dialog = new DialogDerivar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblDependencia;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JTable tableListTramites;
    private javax.swing.JTextField txtCodigoTramite;
    private javax.swing.JTextField txtDependenciaDestino;
    private javax.swing.JTextField txtDiasTranscurridos;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtMotivoEnvio;
    private javax.swing.JTextField txtSolicitante;
    private javax.swing.JTextField txtTipoTramite;
    // End of variables declaration//GEN-END:variables
    
    private LoginResponseDTO loginResponseDTO;
    private ServicesTramite serviceTramite;
    private QuerysTramite queryTramite;
    private List<TramiteQuerysDTO> listTramite;
    private final String cabecera[] = {"COD. TRAMITE", "TIPO TRAMITE", /*"ASUNTO", */"SOLICITANTE", "DERIVAR A... "};
    private DefaultTableModel tableModel;
    private int rowNumSelected = -1;
    
    private void initProcess() {
        if(serviceTramite==null) {
            serviceTramite = new ServicesTramiteImp();
        }
        if(queryTramite==null) {
            queryTramite = new QueryTramiteImp();
        }
        loadUsuario();
        nuevo();
    }
    
    private void loadUsuario() {
        lblNombreUsuario.setText(loginResponseDTO.getNombreUsuario());
        lblDependencia.setText(loginResponseDTO.getNombreDependencia());
        lblArea.setText(loginResponseDTO.getNombreArea());
    }
    
    public void nuevo() {
        rowNumSelected = -1;
        loadTramiteToDeriverByDependency();
        txtCodigoTramite.setText("");
        txtDependenciaDestino.setText("");
        txtMotivoEnvio.setText("");
        txtSolicitante.setText("");
        txtTipoTramite.setText("");
        tableListTramites.setModel(tableModel);
        txtDuracion.setText("");
        txtDiasTranscurridos.setText("");
        lblAlerta.setText("");
    }
    
    private void loadTramiteToDeriverByDependency() {
        //tableListTramites.setAutoResizeMode(tableListTramites.AUTO_RESIZE_LAST_COLUMN);
        tableModel = new DefaultTableModel(cabecera, 0);
        listTramite = queryTramite.listTramitesToDeriverByDependency(loginResponseDTO.getIdDependencia());
        //String cabecera[] = {"COD. TRAMITE", "TIPO TRAMITE", "ASUNTO", "SOLICITANTE", "DERIVAR A... "};
        for(TramiteQuerysDTO t : listTramite) {
            String data[] = {t.getCodigoTramite(), t.getTipoTramite(), /*t.getAsunto(), */t.getSolicitante(), t.getDependenciaDestino()};
            tableModel.addRow(data);
        }
        tableListTramites.setModel(tableModel);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de trámites a derivar. (" + listTramite.size() + " trámites)"));
    }
    
    private void seleccionarTramite(){
        rowNumSelected = tableListTramites.getSelectedRow();
        TramiteQuerysDTO tramiteSelected = listTramite.get(rowNumSelected);
        txtCodigoTramite.setText(tramiteSelected.getCodigoTramite());
        txtTipoTramite.setText(tramiteSelected.getTipoTramite());
        txtSolicitante.setText(tramiteSelected.getSolicitante());
        txtDependenciaDestino.setText(tramiteSelected.getDependenciaDestino());
        txtDuracion.setText(String.valueOf(tramiteSelected.getDuracion()));
        txtDiasTranscurridos.setText(String.valueOf(tramiteSelected.getDiasTranscurridos()));
        int diferenciaDias = tramiteSelected.getDuracion() - tramiteSelected.getDiasTranscurridos();
        if(diferenciaDias>0) {
            String mensaje = "Al trámite le quedan " + diferenciaDias + " días";
            lblAlerta.setForeground(new java.awt.Color(0, 0, 204));
            lblAlerta.setText(mensaje);
        }else {
            String mensaje = "Al trámite se ha pasado por  " + diferenciaDias * (-1) + " días";
            lblAlerta.setForeground(new java.awt.Color(255, 0, 0));
            lblAlerta.setText(mensaje);
        }
        txtMotivoEnvio.requestFocus();
    }
    
    private TramiteMovimientoDTO cargarDatos() {
        TramiteDTO tramiteDto = new TramiteDTO("TR0000");
        if(rowNumSelected>=0) {
            tramiteDto = new TramiteDTO(listTramite.get(rowNumSelected).getCodigoTramite());
        }
        String motivoEnvio = txtMotivoEnvio.getText();
        TramiteMovimientoDTO tramiteMovimientoDto = new TramiteMovimientoDTO(motivoEnvio, tramiteDto);
        return tramiteMovimientoDto;
    }
    
    private void procesar() {
        HttpResponse<String> response = serviceTramite.deriver(cargarDatos());
        Map<String, Object> mapResponse = new Gson().fromJson(response.body(), new TypeToken<HashMap<String, Object>>() {}.getType());
        String mensaje = (String) mapResponse.get("mensaje");
        int messageType = JOptionPane.WARNING_MESSAGE;
        if((boolean) mapResponse.get("flag")) {
            nuevo();
            messageType = JOptionPane.INFORMATION_MESSAGE;
        }
        JOptionPane.showMessageDialog(this, mensaje, "Respuesta", messageType);
        
    }

}
