/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pe.com.softlite.clientsistradoc.view.process;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import pe.com.softlite.clientsistradoc.dto.LoginResponseDTO;
import pe.com.softlite.clientsistradoc.dto.SolicitanteDTO;
import pe.com.softlite.clientsistradoc.dto.TipoTramiteDTO;
import pe.com.softlite.clientsistradoc.dto.TramiteDTO;
import pe.com.softlite.clientsistradoc.dto.TramiteRegisterDTO;
import pe.com.softlite.clientsistradoc.process.ServicesTramite;
import pe.com.softlite.clientsistradoc.process.imp.ServicesTramiteImp;
import java.net.http.HttpResponse;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class DialogRegistrar extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public DialogRegistrar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initProcess();
    }
    
    public DialogRegistrar(java.awt.Frame parent, boolean modal, LoginResponseDTO loginResponseDTO) {
        super(parent, modal);
        this.loginResponseDTO = loginResponseDTO;
        initComponents();
        initProcess();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbTramiteTipoTramite = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtTramiteAsunto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbTramiteTipoDocumento = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtTramiteNroFolios = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTramiteObservacion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbSolicitanteTipoSolicitante = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbSolicitanteTipoDocumento = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtSolicitanteNroDocumento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSolicitanteNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSolicitanteApellidoPaterno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSolicitanteApellidoMaterno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSolicitanteTelefono = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSolicitanteCorreo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSolicitanteRepresentante = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proceso registrar trámites");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del tramite"));
        jPanel1.setName("DatosTram"); // NOI18N

        jLabel1.setText("Tipo de Trámite *");

        cbTramiteTipoTramite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Asunto *");

        jLabel3.setText("Tipo Documento *");

        cbTramiteTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLICITUD", "OFICIO", "CARTA", "OTROS" }));

        jLabel4.setText("Nro de Folios");

        txtTramiteNroFolios.setText("1");

        jLabel8.setText("Observacion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTramiteAsunto, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(cbTramiteTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(106, 106, 106)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(txtTramiteNroFolios, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtTramiteObservacion)
                        .addComponent(cbTramiteTipoTramite, 0, 494, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTramiteTipoTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTramiteAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTramiteTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTramiteNroFolios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTramiteObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del Solicitante"));

        jLabel5.setText("Tipo Solicitante *");

        cbSolicitanteTipoSolicitante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PERSONA", "ENTIDAD" }));

        jLabel6.setText("Tipo Documento *");

        cbSolicitanteTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "CE", "PAS", "RUC" }));

        jLabel7.setText("Nro Documento *");

        jLabel9.setText("Nombres *");

        jLabel10.setText("Apellido Paterno *");

        jLabel11.setText("Apellido Materno *");

        jLabel12.setText("Telefono");

        jLabel13.setText("e-mail");

        jLabel14.setText("Representante");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSolicitanteRepresentante)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbSolicitanteTipoDocumento, 0, 159, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addComponent(txtSolicitanteNombre)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSolicitanteApellidoPaterno)
                                    .addComponent(txtSolicitanteTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSolicitanteNroDocumento)
                            .addComponent(txtSolicitanteApellidoMaterno)
                            .addComponent(txtSolicitanteCorreo)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbSolicitanteTipoSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbSolicitanteTipoSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbSolicitanteTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtSolicitanteNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSolicitanteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSolicitanteApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtSolicitanteApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSolicitanteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtSolicitanteCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtSolicitanteRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistrar);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Dats");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogRegistrar dialog = new DialogRegistrar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbSolicitanteTipoDocumento;
    private javax.swing.JComboBox<String> cbSolicitanteTipoSolicitante;
    private javax.swing.JComboBox<String> cbTramiteTipoDocumento;
    private javax.swing.JComboBox<String> cbTramiteTipoTramite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtSolicitanteApellidoMaterno;
    private javax.swing.JTextField txtSolicitanteApellidoPaterno;
    private javax.swing.JTextField txtSolicitanteCorreo;
    private javax.swing.JTextField txtSolicitanteNombre;
    private javax.swing.JTextField txtSolicitanteNroDocumento;
    private javax.swing.JTextField txtSolicitanteRepresentante;
    private javax.swing.JTextField txtSolicitanteTelefono;
    private javax.swing.JTextField txtTramiteAsunto;
    private javax.swing.JTextField txtTramiteNroFolios;
    private javax.swing.JTextField txtTramiteObservacion;
    // End of variables declaration//GEN-END:variables
    
    private ServicesTramite serviceTramite;
    private List<TipoTramiteDTO> listTipoTramiteDto;
    private LoginResponseDTO loginResponseDTO;
    
    private void initProcess() {
        if(serviceTramite==null) {
            serviceTramite = new ServicesTramiteImp();
        }
            
        //Cargar los datos de tipo de trámite
        loadListTipoTramite();
        nuevo();
    }
    
    private void loadListTipoTramite() {
        cbTramiteTipoTramite.removeAllItems();
        listTipoTramiteDto = serviceTramite.listTipoTramite();
        for(TipoTramiteDTO tipoTramite : listTipoTramiteDto) {
            cbTramiteTipoTramite.addItem(tipoTramite.getNombreTipoTramite());
        }
    }
    
    private void nuevo() {
        
        cbTramiteTipoTramite.setSelectedIndex(0);
        txtTramiteAsunto.setText("");
        cbTramiteTipoDocumento.setSelectedIndex(0);
        txtTramiteNroFolios.setText("1");
        txtTramiteObservacion.setText("");
        
        cbSolicitanteTipoSolicitante.setSelectedIndex(0);
        cbSolicitanteTipoDocumento.setSelectedIndex(0);
        txtSolicitanteNroDocumento.setText("");
        txtSolicitanteNombre.setText("");
        txtSolicitanteApellidoPaterno.setText("");
        txtSolicitanteApellidoMaterno.setText("");
        txtSolicitanteTelefono.setText("");
        txtSolicitanteCorreo.setText("");
        txtSolicitanteRepresentante.setText("");
    }
    
    private void registrar() {
        HttpResponse<String> response = serviceTramite.register(cargarDatos());
        Map<String, Object> mapResponse = new Gson().fromJson(response.body(), new TypeToken<HashMap<String, Object>>() {}.getType());
        String mensaje = (String) mapResponse.get("mensaje");
        String codigoTramite;
        int messageType = JOptionPane.WARNING_MESSAGE;
        if((boolean) mapResponse.get("flag")) {
            Map<String, Object> data = (Map<String, Object>) mapResponse.get("data");
            codigoTramite = (String) data.get("codigoTramite");
            nuevo();
            messageType = JOptionPane.INFORMATION_MESSAGE;
            JOptionPane.showMessageDialog(this, mensaje + ". El código generado es: " + codigoTramite, "Respuesta", messageType);
        }else {
            JOptionPane.showMessageDialog(this, mensaje, "Respuesta", messageType);
        }
        
    }
    
    private TramiteRegisterDTO cargarDatos() {
        TipoTramiteDTO tipoTramiteDto = listTipoTramiteDto.get(cbTramiteTipoTramite.getSelectedIndex());
        
        SolicitanteDTO solicitanteDto = new SolicitanteDTO(txtSolicitanteNroDocumento.getText(), 
                                                           cbSolicitanteTipoDocumento.getSelectedItem().toString(), 
                                                           cbSolicitanteTipoSolicitante.getSelectedItem().toString(), 
                                                           txtSolicitanteNombre.getText(), 
                                                           txtSolicitanteApellidoPaterno.getText(), 
                                                           txtSolicitanteApellidoMaterno.getText(), 
                                                           txtSolicitanteCorreo.getText(), 
                                                           null, 
                                                           txtSolicitanteTelefono.getText(), 
                                                           txtSolicitanteRepresentante.getText());
        
        TramiteDTO tramiteDto = new TramiteDTO(txtTramiteAsunto.getText(), 
                                               txtTramiteObservacion.getText(), 
                                               Integer.valueOf(txtTramiteNroFolios.getText()), 
                                               "Sin Referencia", 
                                               cbTramiteTipoDocumento.getSelectedItem().toString(), 
                                               tipoTramiteDto, 
                                               solicitanteDto);
        
        return new TramiteRegisterDTO(tramiteDto);
    }

}
