/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.com.softlite.clientsistradoc.view;

import pe.com.softlite.clientsistradoc.dto.LoginResponseDTO;
import pe.com.softlite.clientsistradoc.view.process.DialogFinalizar;
import pe.com.softlite.clientsistradoc.view.process.DialogDevolver;
import pe.com.softlite.clientsistradoc.view.process.DialogRegistrar;
import pe.com.softlite.clientsistradoc.view.process.DialogDerivar;
import pe.com.softlite.clientsistradoc.view.process.DialogRegistrarTarea;
import pe.com.softlite.clientsistradoc.view.querys.DialogBusquedaTramite;

/**
 *
 * @author USER
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public JFramePrincipal() {
        initComponents();
        initProcess();
    }
    
    public JFramePrincipal(LoginResponseDTO loginResponseDTO) {
        this.loginResponseDTO = loginResponseDTO;
        initComponents();
        initProcess();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemRegistrarTramite = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemRegistrarTareas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemDerivarTramites = new javax.swing.JMenuItem();
        itemDevolverTramites = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itemFinalizarTramites = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemBusquedaTramite = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE TRÁMITE DOCUMENTARIO");

        jMenu2.setText("File");

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        jMenu2.add(itemSalir);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Procesos");

        itemRegistrarTramite.setText("Registrar Tramite");
        itemRegistrarTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarTramiteActionPerformed(evt);
            }
        });
        jMenu3.add(itemRegistrarTramite);
        jMenu3.add(jSeparator1);

        itemRegistrarTareas.setText("Registrar Tareas y/o actividades en tramite");
        itemRegistrarTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarTareasActionPerformed(evt);
            }
        });
        jMenu3.add(itemRegistrarTareas);
        jMenu3.add(jSeparator2);

        itemDerivarTramites.setText("Derivar Documentos");
        itemDerivarTramites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDerivarTramitesActionPerformed(evt);
            }
        });
        jMenu3.add(itemDerivarTramites);

        itemDevolverTramites.setText("Devolver Documentos");
        itemDevolverTramites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDevolverTramitesActionPerformed(evt);
            }
        });
        jMenu3.add(itemDevolverTramites);
        jMenu3.add(jSeparator3);

        itemFinalizarTramites.setText("Finalizar Trámites");
        itemFinalizarTramites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFinalizarTramitesActionPerformed(evt);
            }
        });
        jMenu3.add(itemFinalizarTramites);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas & Seguimientos");

        itemBusquedaTramite.setText("Busqueda de trámites");
        itemBusquedaTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBusquedaTramiteActionPerformed(evt);
            }
        });
        jMenu4.add(itemBusquedaTramite);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemRegistrarTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarTramiteActionPerformed
        loadRegistrarTramite();
    }//GEN-LAST:event_itemRegistrarTramiteActionPerformed

    private void itemRegistrarTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarTareasActionPerformed
        loadRegistrarTareas();
    }//GEN-LAST:event_itemRegistrarTareasActionPerformed

    private void itemDerivarTramitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDerivarTramitesActionPerformed
        loadDerivarTramites();
    }//GEN-LAST:event_itemDerivarTramitesActionPerformed

    private void itemDevolverTramitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDevolverTramitesActionPerformed
        loadDevolverTramites();
    }//GEN-LAST:event_itemDevolverTramitesActionPerformed

    private void itemFinalizarTramitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFinalizarTramitesActionPerformed
        loadFinalizarTramite();
    }//GEN-LAST:event_itemFinalizarTramitesActionPerformed

    private void itemBusquedaTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBusquedaTramiteActionPerformed
        loadBusquedaTramite();
    }//GEN-LAST:event_itemBusquedaTramiteActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(1);
    }//GEN-LAST:event_itemSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemBusquedaTramite;
    private javax.swing.JMenuItem itemDerivarTramites;
    private javax.swing.JMenuItem itemDevolverTramites;
    private javax.swing.JMenuItem itemFinalizarTramites;
    private javax.swing.JMenuItem itemRegistrarTareas;
    private javax.swing.JMenuItem itemRegistrarTramite;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables

    private LoginResponseDTO loginResponseDTO;
    private DialogRegistrar dialogRegistrarTramite;
    private DialogRegistrarTarea dialogRegistrarTarea;
    private DialogDerivar dialogDerivarTramite;
    private DialogDevolver dialogDevolverTramite;
    private DialogFinalizar dialogFinalizarTramite;
    
    private DialogBusquedaTramite dialogBusquedaTramite;
    
    private void initProcess() {
        if(dialogRegistrarTramite==null) {
            dialogRegistrarTramite = new DialogRegistrar(this, true, loginResponseDTO);
        }
        if(dialogRegistrarTarea==null) {
            dialogRegistrarTarea = new DialogRegistrarTarea(this, true, loginResponseDTO);
        }
        if(dialogDerivarTramite==null) {
            dialogDerivarTramite = new DialogDerivar(this, true, loginResponseDTO);
        }
        if(dialogDevolverTramite==null) {
            dialogDevolverTramite = new DialogDevolver(this, true, loginResponseDTO);
        }
        if(dialogFinalizarTramite==null) {
            dialogFinalizarTramite = new DialogFinalizar(this, true, loginResponseDTO);
        }
        if(dialogBusquedaTramite==null) {
            dialogBusquedaTramite = new DialogBusquedaTramite(this, true, loginResponseDTO);
        }
    }
    
    private void loadRegistrarTramite() {
        dialogRegistrarTramite.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogRegistrarTramite.pack();
        dialogRegistrarTramite.setVisible(true);
    }
    
    private void loadRegistrarTareas() {
        dialogRegistrarTarea.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogRegistrarTarea.nuevo();
        dialogRegistrarTarea.pack();
        dialogRegistrarTarea.setVisible(true);
    }
    
    private void loadDerivarTramites() {
        dialogDerivarTramite.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogDerivarTramite.nuevo();
        dialogDerivarTramite.pack();
        dialogDerivarTramite.setVisible(true);
    }
    
    private void loadDevolverTramites() {
        dialogDevolverTramite.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogDevolverTramite.nuevo();
        dialogDevolverTramite.pack();
        dialogDevolverTramite.setVisible(true);
    }
    
    private void loadFinalizarTramite() {
        dialogFinalizarTramite.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogFinalizarTramite.nuevo();
        dialogFinalizarTramite.pack();
        dialogFinalizarTramite.setVisible(true);
    }
    
    private void loadBusquedaTramite() {
        dialogBusquedaTramite.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogBusquedaTramite.nuevo();
        dialogBusquedaTramite.pack();
        dialogBusquedaTramite.setVisible(true);
    }

    public LoginResponseDTO getLoginResponseDTO() {
        return loginResponseDTO;
    }
    
}
